theme: jekyll-theme-dinky
title: Keizaal
tagline: A Simple Modlist
description: Keizaal is a simple modlist that seeks to enhance and expand on Skyrim without compromising Bethesda’s original vision that we all fell in love with back in 2011.
baseurl: /
wabbajack:
  wabbajack_url: https://www.wabbajack.org/#/
utterances:
  repo: Keizaal/Keizaal-Testimonials
  issue_number: 1
  theme: github-dark
