title: Keizaal
tagline: A Simple Modlist
description: Keizaal is a simple modlist that seeks to enhance and expand on Skyrim without compromising Bethesda’s original vision that we all fell in love with back in 2011.
url: https://keiza.al

defaults:
  - scope:
      path: ""
    values:
      layout: page
      image: "https://keiza.al/assets/img/thumbnail.png"

plugins:
  - jekyll-redirect-from

utterances:
  theme: github-dark
