title: Keizaal
tagline: A Simple Modlist
description: Keizaal is a simple modlist that seeks to enhance and expand on Skyrim without compromising Bethesda’s original vision that we all fell in love with back in 2011.
url: https://keiza.al

defaults:
  - scope:
      path: ""
    values:
      layout: default
      image: https://github.com/Keizaal/Keizaal/blob/main/assets/img/branding/banners/Standard.png

utterances:
  theme: github-dark
